[package]
name = "cologne_codes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
unsafe_opt = []

[dependencies]

[[example]]
name = "cologne_cat"
opt-level = 3
codegen-units = 1
lto = "fat"

